[package]
name = "fljuga-handahofi-tablegen"
description = ""
version = "0.1.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
winnow.workspace = true
mutants.workspace = true

[lints]
workspace = true